version: '3.3'

services: 
  mysql:
    image: mysql
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: air
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    
  app:
    image: babakoto5/air-quality
    environment:
        PORT: 3000
    ports:
      - "8080:3000"
    depends_on:
      - mysql
    stdin_open: true
    tty: true
